# vim:ft=kitty

## name: Árvore Light
## license: MIT
## author: Árvore Theme
## upstream: https://github.com/arvore-theme

background #F9FCFF
foreground #053B4B
selection_background #C9F4ED
selection_foreground #053B4B
url_color #40CAB6
cursor #40CAB6
cursor_text_color #FFFFFF

# Tabs
active_tab_background #40CAB6
active_tab_foreground #FFFFFF
inactive_tab_background #F1F7FB
inactive_tab_foreground #7C98A1

# Windows
active_border_color #40CAB6
inactive_border_color #DEE1E6

# normal
color0 #151E23
color1 #FA163E
color2 #3DA169
color3 #FDD351
color4 #4F81F1
color5 #8764D8
color6 #40CAB6
color7 #F1F7FB

# bright
color8  #7C98A1
color9  #FA5371
color10 #7FC923
color11 #FDC200
color12 #6394F3
color13 #9272DC
color14 #66DCCE
color15 #F9FCFF

# extended colors
color16 #FB673A
color17 #FA163E
